### PR TITLE
First draft documentation

### PR DESCRIPTION
**Pull request by allthesignals**
I've migrated everything from README and API markdown files into an `ember-cli-addon-docs` structure. This adds several YUIDocs changes into the actual source files themselves. 

There's still work left to do in terms of:

 - [ ] Walkthrough Guide
 - [x] Better introduction
 - [ ] Better splash page
 - [x] Other pages
 - [ ] Some API docs are incomplete (missing proper YUIDocs for properties/arguments

I wanted to get this up here so others can see the branch.

In terms of deployment, there are lots of options, but it's hard to troubleshoot deployment issues without permissions in the repo.

### CODE REVIEW

**Comment by allthesignals** [comment]
Find a staging version of the site here: https://allthesignals.github.io/ember-mapbox-gl/

I need to rewrite some of the narrative pages (Intro, etc). Anyone have any inspiration, ideas?

**Comment by allthesignals** [comment]
Not sure why that test is failing:

```
not ok 110 Firefox 62.0 - [329 ms] - Integration | Component | mapbox gl image: it only adds the latest image if image is updated before the previous image finishes loading
    ---
        actual: >
            false
        expected: >
            true
        stack: >
            _callee4$@http://localhost:7357/assets/tests.js:6305:17
            tryCatch@http://localhost:7357/assets/vendor.js:406:37
            invoke@http://localhost:7357/assets/vendor.js:680:22
            defineIteratorMethods/</prototype[method]@http://localhost:7357/assets/vendor.js:439:16
            step@http://localhost:7357/assets/tests.js:6113:24
            step/<@http://localhost:7357/assets/tests.js:6124:15
            
        message: >
            addImage called
        negative: >
            false
        Log: |
    ...
```

For Ember 2.16.

**Comment by kturney** [comment]
looks like it may just be a flakey test. I think I'm just gonna merge and get deploying. any objections?

**Comment by allthesignals** [comment]
@kturney sounds good. I'll continue to contribute writing. Lemme know if you have trouble with deploying.

**Comment by allthesignals** [comment]
@kturney sounds good. I'll continue to contribute writing. Lemme know if you have trouble with deploying.

**Comment by allthesignals** [comment]
@kturney sounds good. I'll continue to contribute writing. Lemme know if you have trouble with deploying.

**Comment by allthesignals** [comment]
@kturney sounds good. I'll continue to contribute writing. Lemme know if you have trouble with deploying.

**Pull request merged**
