### PR TITLE
Yield the mapbox instance to enable making alternative mapbox components  and helpers

### PR DESCRIPTION
**Pull request by kategengler**

### CODE REVIEW

**Review by kturney — APPROVED** [review]
Makes sense to me!

**Comment by kategengler** [comment]
Thanks for merging!

**Comment by kturney** [comment]
thanks for all your work in the ember community! 😀
I'm gonna do some dep upgrades, fix some deprecations, and then get a new version published.

**Comment by kturney** [comment]
published in 0.14.0

**Pull request merged**
